# Задача 1
def test_function():  # определение "внешней" функции

    def inner_function():  # определение "внутренней" функции
        print('Я в области видимости функции test_function')  # вывод такста

    inner_function()  # вызов "внутренней" функции в пространстве имён внейшей функции (объемлющей для "внутренней" функции)


test_function()  # вызов "внешней" функции в глобальном пространстве
# выполнение без ошибок

# Задача 2


def test_function():  # определение "внешней" функции

    def inner_function():  # определение "внутренней" функции
        print('Я в области видимости функции test_function')  # вывод такста

    inner_function()  # вызов "внутренней" функции в пространстве имён внейшей функции (объемлющей для "внутренней" функции)


inner_function()
# вызов "внутренней" функции из области глобального пространства имён приведёт к ошибке определения объекта 'inner_function'
# поскольку объект определяется при выполнении test_function и располагается в её локальном пространстве имён
